/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.стена} position={[0.1, 3.46, -3.6]} rotation={[Math.PI / 2, 0, 0]} scale={[4.17, 0.5, 3.48]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.стена} position={[-4.18, 3.44, -0.18]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-3.95, -0.16, -3.48]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials.Подколодник} position={[0.1, 3.46, -4.07]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-5.67, -0.03, -3.48]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials.glasss} position={[0.1, 3.46, -4.09]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-5.67, 0, -3.48]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials.glasss} position={[0.1, 3.46, -4.09]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-5.67, 0, -3.48]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0.14, 3.63, -3.99]} rotation={[-Math.PI, 0.07, -Math.PI]} scale={[0.04, 0.08, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Ножки} position={[-2.56, 0.84, -1.87]} scale={[1.32, 1.63, 1.23]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Ножки} position={[-2.56, 0.84, 0.64]} scale={[1.32, 1.6, 1.23]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.Ножки} position={[-1.25, 0.84, 0.64]} scale={[1, 1.62, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials.Ножки} position={[-1.25, 0.84, -1.87]} scale={[1, 1.58, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.Подколодник} position={[0.11, 2.08, -3.57]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.25, -0.06, -0.52]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.Подколодник} position={[0.24, 1.1, -3.06]} scale={[0.93, 0.57, 0.06]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials.Стол} position={[-1.69, 1.86, -0.67]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.19, -0.04, -1.81]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-4.1, 0.05, -0.06]} scale={[4.3, 0.16, 3.87]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials['Material.011']} position={[-1.55, 1.9, -1.34]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.3, -0.01, -0.73]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials.столик} position={[2.94, 0.63, -1.49]} scale={[1, 0.08, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.столик} position={[3.79, 0.28, -0.81]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.28, -0.06, -0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube017.geometry} material={materials.столик} position={[2.31, 0.28, -0.6]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.28, -0.06, -0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube019.geometry} material={materials.столик} position={[3.57, 0.3, -0.59]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.28, -0.06, -0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube020.geometry} material={materials.столик} position={[3.79, 0.28, -2.17]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.28, -0.06, -0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube021.geometry} material={materials.столик} position={[2.09, 0.28, -0.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.28, -0.06, -0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube022.geometry} material={materials.столик} position={[2.47, 0.28, -2.36]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.28, -0.06, -0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials.Системник} position={[-3.13, 0.22, 0.14]} scale={0.21} />
      <mesh castShadow receiveShadow geometry={nodes.Cube023.geometry} material={materials.Розетка} position={[-2.25, 0.05, 0.2]} rotation={[0, -0.09, 0]} scale={[0.09, 0.04, 0.27]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube025.geometry} material={materials.Розетка} position={[-4.03, 0.33, 1.27]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.06, 0.1, 0.1]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials.Штекер} position={[-3.96, 0.33, 1.25]} rotation={[0, 0, -1.59]} scale={[0.51, 0.06, 0.51]} />
      <mesh castShadow receiveShadow geometry={nodes.BezierCurve001.geometry} material={materials.Шнур} position={[-2.75, 0.5, 1.44]} rotation={[-0.06, 0, 0]} scale={[0.79, 1, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={materials.Розетка} position={[-2.28, 0.04, 0.48]} rotation={[1.6, -0.06, 3.05]} scale={[0.25, 0.04, 0.32]} />
      <group position={[-2.23, 0.43, -1.56]} scale={[0.59, 0.44, 0.24]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube046_1.geometry} material={materials.Системник} />
        <mesh castShadow receiveShadow geometry={nodes.Cube046_2.geometry} material={nodes.Cube046_2.material} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube028.geometry} material={materials.glasss} position={[-2.23, 0.43, -1.36]} scale={[0.59, 0.44, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.BezierCurve002.geometry} material={materials.Шнур} position={[-1.55, 0.38, 0.72]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={materials.Штекер} position={[-2.28, 0.08, 0.38]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.38, -0.08, -0.38]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007.geometry} material={materials.Штекер} position={[-2.27, 0.08, 0.25]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.38, -0.08, -0.38]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder008.geometry} material={materials.Штекер} position={[-2.26, 0.05, 0.12]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.38, -0.08, -0.38]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder009.geometry} material={materials.glasss} position={[-1.96, 2.04, 0.61]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.57, -0.11, -1.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder011.geometry} material={materials.Material} position={[-1.96, 1.93, 0.61]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.57, -0.07, -1.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Text.geometry} material={materials.Material} position={[-3.95, 4.52, 2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.72} />
      <mesh castShadow receiveShadow geometry={nodes.Text001.geometry} material={materials.Material} position={[-3.97, 3.63, 3.13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials.ковёр} position={[1.62, 0.03, -0.11]} scale={2.57} />
      <group position={[-1.67, 4, -3.07]} rotation={[0, 0, -Math.PI]} scale={[0.28, 0.36, 0.05]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.provod} />
        <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-2.44, 2.61, -0.65]} scale={[0.03, 0.44, 0.85]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube012_1.geometry} material={materials.монитор} />
        <mesh castShadow receiveShadow geometry={nodes.Cube012_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-3.47, 2.45, -2.83]} scale={0.28}>
        <mesh castShadow receiveShadow geometry={nodes.Cube014_1.geometry} material={materials.монитор} />
        <mesh castShadow receiveShadow geometry={nodes.Cube014_2.geometry} material={materials['Material.007']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.монитор} position={[-2.08, 1.91, -2.02]} rotation={[-Math.PI, 0.83, -Math.PI]} scale={[0.14, 0.02, 0.14]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube034.geometry} material={materials['Material.010']} position={[0.25, 3.13, -2.52]} scale={[1.13, 1.76, 1.07]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[-1.66, 1.94, -0.23]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[-1.6, 1.94, -0.24]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[-1.54, 1.94, -0.27]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[-1.72, 1.94, -0.19]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[-1.78, 1.94, -0.26]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[-1.78, 1.94, -0.53]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} position={[-1.78, 1.94, -0.79]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[-1.78, 1.95, -1.05]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[-1.71, 1.95, -1.05]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[-1.65, 1.95, -1.05]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[-1.48, 1.95, -1.04]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} position={[-1.54, 1.95, -1.1]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} position={[-1.48, 1.94, -0.14]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[-1.48, 1.94, -0.74]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[-1.78, 1.94, -0.14]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} position={[-1.72, 1.94, -0.14]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} position={[-1.66, 1.94, -0.14]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} position={[-1.6, 1.94, -0.14]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[-1.54, 1.94, -0.14]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[-1.48, 1.94, -0.36]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[-1.53, 1.95, -0.87]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} position={[-1.6, 1.95, -0.9]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube057.geometry} material={nodes.Cube057.material} position={[-1.66, 1.95, -0.94]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube058.geometry} material={nodes.Cube058.material} position={[-1.72, 1.95, -0.91]} rotation={[0.01, 1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube059.geometry} material={materials.keyboard} position={[-1.63, 1.91, -0.65]} rotation={[0.01, 1.57, 0]} scale={[0.55, 0.01, 0.2]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube060.geometry} material={materials['Material.005']} position={[-1.63, 1.92, -0.66]} rotation={[0.01, 1.57, 0]} scale={[0.54, 0.01, 0.18]} />
      <mesh castShadow receiveShadow geometry={nodes.BezierCurve007.geometry} material={materials.Шнур} position={[-1.63, 2.31, -0.66]} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere002.geometry} material={materials.keyboard} position={[-1.66, 1.92, -1.43]} scale={[0.13, 0.05, 0.08]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder015.geometry} material={materials['mouse wheel']} position={[-1.75, 1.95, -1.43]} rotation={[-1.63, 0, -Math.PI]} scale={[0.02, 0.01, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} position={[-1.75, 1.95, -1.43]} rotation={[-1.58, 0, 0]} scale={[0, -0.02, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube061.geometry} material={nodes.Cube061.material} position={[-2.44, 0.45, -1.46]} rotation={[0, 0, -Math.PI]} scale={[-0.23, -0.03, -0.09]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube062.geometry} material={materials.сидушка} position={[-0.04, 1.29, -1.07]} rotation={[-Math.PI, 0.61, -Math.PI]} scale={[-0.63, -0.09, -0.6]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.сидушка} position={[0, 1.27, -1.13]} rotation={[0, -0.61, 0]} scale={[0.53, 0.66, 0.53]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder017.geometry} material={materials.ручка} position={[0.55, 1.46, -0.76]} rotation={[0, -0.61, 0]} scale={[-0.03, -0.3, -0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder018.geometry} material={materials.ручка} position={[-0.57, 1.46, -1.54]} rotation={[0, -0.61, 0]} scale={[-0.03, -0.3, -0.03]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube063.geometry} material={materials.ручка} position={[-0.01, 1.16, -1.15]} rotation={[0, -0.61, -Math.PI]} scale={[0.73, 0.01, 0.05]} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere003.geometry} material={materials.Розетка} position={[0.58, 1.77, -0.79]} rotation={[-Math.PI, 0.82, -Math.PI]} scale={[0.06, 0.03, 0.39]} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere004.geometry} material={materials.Розетка} position={[-0.55, 1.77, -1.57]} rotation={[0, -0.34, 0]} scale={[0.06, 0.03, 0.39]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder019.geometry} material={materials.ручка} position={[0, 0.67, -1.11]} rotation={[0, -1.55, 0]} scale={[0.07, 0.53, 0.07]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube065.geometry} material={materials.ручка} position={[-0.4, 0.14, -1.08]} rotation={[-Math.PI, 1.5, 0]} scale={[-0.05, -0.02, -0.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube064.geometry} material={materials.ручка} position={[-0.14, 0.14, -1.5]} rotation={[0, 0.35, -Math.PI]} scale={[-0.05, -0.02, -0.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube066.geometry} material={materials.ручка} position={[0.29, 0.14, -1.4]} rotation={[0, -0.77, -Math.PI]} scale={[-0.05, -0.02, -0.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube067.geometry} material={materials.ручка} position={[0.32, 0.14, -0.85]} rotation={[Math.PI, -0.92, 0]} scale={[-0.05, -0.02, -0.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube068.geometry} material={materials.ручка} position={[-0.08, 0.14, -0.72]} rotation={[0, -0.19, -Math.PI]} scale={[-0.05, -0.02, -0.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder020.geometry} material={materials.Шнур} position={[-0.72, 0.07, -1.07]} rotation={[0, 0, 1.61]} scale={0.06} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder021.geometry} material={materials.Шнур} position={[-0.16, 0.07, -0.41]} rotation={[0, -0.51, 1.61]} scale={0.06} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder022.geometry} material={materials.Шнур} position={[0.58, 0.07, -0.65]} rotation={[0, -0.51, 1.61]} scale={0.06} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder023.geometry} material={materials.Шнур} position={[0.48, 0.07, -1.65]} rotation={[Math.PI, -1.52, -1.53]} scale={0.06} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder024.geometry} material={materials.Шнур} position={[-0.27, 0.07, -1.81]} rotation={[0, -0.61, 1.61]} scale={0.06} />
    </group>
  )
}

useGLTF.preload('/house.glb')
